"""ReportLab report generation integration point."""

from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_report(data: dict, output_path: str) -> str:
    """Generate a report and return its output path once configured."""
    return output_path


def generate_pdf(data: dict) -> BytesIO:
    """Generate a compact inspection PDF for download."""
    stream = BytesIO()
    document = canvas.Canvas(stream, pagesize=A4)
    width, height = A4
    document.setTitle("NIRIKSHA Compliance Report")
    document.setFillColorRGB(0.06, 0.24, 0.39)
    document.setFont("Helvetica-Bold", 20)
    document.drawString(48, height - 64, "NIRIKSHA")
    document.setFont("Helvetica", 10)
    document.setFillColorRGB(0.25, 0.3, 0.35)
    document.drawString(48, height - 84, "Legal Metrology Compliance Report")
    document.line(48, height - 98, width - 48, height - 98)
    document.setFont("Helvetica-Bold", 12)
    document.drawString(48, height - 132, "Inspection Summary")
    document.setFont("Helvetica", 10)
    summary = data.get("summary", {})
    lines = [
        f"Inspection ID: {data.get('id', 'demo-inspection')}",
        f"Product: {summary.get('product_name', 'N/A')}",
        f"Inspector: {summary.get('inspector', 'N/A')}",
        f"Compliance status: {data.get('status', 'MINOR VIOLATIONS')}",
        f"Compliance score: {data.get('score', 0)}/100",
    ]
    for index, line in enumerate(lines):
        document.drawString(48, height - 156 - (index * 18), line)
    document.setFont("Helvetica-Oblique", 8)
    document.drawString(48, 42, "Generated by NIRIKSHA. Prototype report pending authorised officer review.")
    document.showPage()
    document.save()
    stream.seek(0)
    return stream
