-- NIRIKSHA private inspection image storage
-- Apply this in the Supabase SQL Editor after 001_init_schema.sql.

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'inspection-images',
  'inspection-images',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- The backend uses SUPABASE_SERVICE_ROLE_KEY for uploads and signed URLs.
-- Service-role requests bypass storage RLS. Keep this bucket private.
--
-- Do not add a public read policy. Images are delivered through short-lived
-- signed URLs generated by the backend after authorization.
--
-- If direct authenticated browser access is needed later, add a narrowly
-- scoped policy after defining the final inspection ownership model.
